# Site settings
title: Cristal-ise
email: your-email@domain.com
keywords: ""
slogen: "Framework to Cope with Change"
tagline: "A Marie-Curie Industry-Academia Partnerships and Pathways project funded by the EU"
description: > # this means to ignore newlines until "baseurl:"
  CRISTAL-ISE was designed to handle the complexity of data-intensive systems and provides the flexibility 
  to adapt to the changing scenarios typical of any production management system, or indeed 
  any process in which workflow and data traceability is crucial, including those employing AI solutions.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
